services:
  wordpress:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WP_IDENTIGRAF_ENDPOINT: ${WP_IDENTIGRAF_ENDPOINT:-}
      WP_IDENTIGRAF_JWT_SECRET: ${WP_IDENTIGRAF_JWT_SECRET:-}
    volumes:
      - ..:/usr/src/wordpress/wp-content/plugins/wp-identigraf
    depends_on:
      - db

  db:
    image: mariadb:10.11@sha256:9ff479f244cc596aed9794d035a9f352662f2caed933238c533024df64569853
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

volumes:
  db:
