name: Static Code Analysis

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  psalm:
    runs-on: ubuntu-latest
    name: Psalm
    steps:
      - name: Check out source code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up PHP
        uses: shivammathur/setup-php@202f1bbec101767690fe929a3ae571c4d19a6b00 # 1.0.0
        with:
          coverage: none

      - name: Install dependencies
        uses: ramsey/composer-install@57532f8be5bda426838819c5ee9afb8af389d51a # 3.0.0

      - name: Run psalm
        run: composer psalm -- --output-format=github
